version: "3.8"

services:
  app:
    build: .
    container_name: url_metadata_scraper
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0

  worker:
    build: .
    container_name: celery_worker
    command: celery -A worker.celery worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0

  redis:
    image: "redis:alpine"
    container_name: redis_server
    ports:
      - "6379:6379"
